import Head from 'next/head'
import Image from 'next/image'       
import { Inter, Fredoka } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/Menu'
import React from 'react';
import Busqueda from '../../fetch-con-api/src/components/Busqueda'

const fredoka = Fredoka({ subsets: ['latin'], weight: '500' })

export default function Home({data}) {
  return (
    <div className={styles.body}>
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png"/> 
      </Head>   

      <div style={fredoka.style} className={styles.header}>

        <div className={styles.left}>
          <a href=""><Menu width={24} height={23}/></a>
          <a href=""> <img className={styles.logo} src="logo-datos.png"/></a>
        </div>
        <div className={styles.center}>
          <a className={styles.nos} href="">NOSOTROS</a>
          <a className={styles.cont} href="">CONTACTO</a>
          <a className={styles.sub} href="">SUBSCRIPCIÓN</a>
        </div>
        <div className={styles.right}>
          <a className={styles.log} href="">Log In</a>
          <a href="" className={styles.lupa}><Busqueda width={24} height={23}/></a>
        </div>

      </div>
      

      <div className={styles.datos}>
      {
          data.map(dat => (
            <div key = {dat.id}>

    <div className={styles.datos}>
      {
          data.map(dat => (
            <div key = {dat.id}>

              <h2 style={fredoka.style} className={styles.resu}> Resultados de trazabilidad</h2>

              <div className={styles.izquierda}>
<<<<<<< HEAD

                <ul className={styles.list}>
                  <li className={styles.item}>
                    <div className={styles.cardRegistro}>
                      <p style={fredoka.style} className={styles.tituloRegistro}>Numero de registro</p>
                      <p style={fredoka.style} className={styles.textoRegistro}>{dat.id}</p>
                      <Image src={'/soleado.png'} width={300} className={styles.soleado} height={300} />
                    </div>
                  </li>

                  <li className={styles.item}>
                    <div className={styles.cardGps}>
                      <p style={fredoka.style} className={styles.tituloGps}>Ubicación</p>
                      <p style={fredoka.style} className={styles.textoGps}>{dat.id} </p>
                      <Image src= {'/ubicacion.png'} width={300} className={styles.gps} height={300} />
=======
                <ul className={styles.list}>
                  <li className={styles.item}>
                    <div className={styles.cardRegistro}>
                      <p className={styles.tituloRegistro}>Numero de registro</p>
                      <p className={styles.textoRegistro}>{dat.id}</p>
                      <Image src={'/soleado.png'} width={300} className={styles.soleado} height={300} />
                    </div>
                  </li>
                  <li className={styles.item}>
                    <div className={styles.cardGps}>
                      <p className={styles.tituloGps}>Ubicacion</p>
                      <p className={styles.textoGps}>{dat.id}</p>
                      <Image src={'/ubicacion.jpg'} width={300} className={styles.gps} height={300} />
>>>>>>> 9251324f625331c3cde42c0675fd12b6110feba8
                    </div>
                  </li>
                </ul>

              </div>

              

            </div>
          ))
      }
    </div>

            </div>
          ))
      }
    </div>
  </div>
  )
}

export const getServerSideProps = async (context)=>{
  const options = {method: 'GET'};
  const res = await fetch("https://bat-simple-api.vercel.app/data", options)
  const datos = await res.json() 
  
    return {
     props: {
       data : datos
     }
   }
}


