import Head from 'next/head'
import Image from 'next/image'       
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title> Prueba API </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/> 
      </Head>     

      <div>
        {
          data.map(dat => (
            <div key = {dat.id}>
              <h4>{dat.humedad}</h4>
              <h4>{dat.temperatura}</h4>
              <h4>{dat.x-pos}</h4>
              <h4>{dat.y-pos}</h4>
              <h4>{dat.tag}</h4>
            </div>
          ))
        }
     </div>

    </div>
  )
}

export const getServerSideProps = async (context)=>{
//const options = {method: 'GET'};
  const res = await fetch("http://bat-simple-api.vercel.app", options)
  const datos = await res.json() 
  
    return {
     props: {
       data : datos
     }
   }
}
