import Head from 'next/head'
import Image from 'next/image'       
import { Inter, Fredoka } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/Menu'


const fredoka = Fredoka({ subsets: ['latin'], weight: '500' })
const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png"/> 
      </Head>   

      <div style={fredoka.style} className={styles.header}>

        <div className={styles.left}>
          <a href=""><Menu width={24} height={23}/></a>
          <a href=""> <img className={styles.logo} src="logo-datos.png"/></a>
        </div>
        <div className={styles.center}>
          <a className={styles.nos} href="">NOSOTROS</a>
          <a className={styles.cont} href="">CONTACTO</a>
          <a className={styles.sub} href="">SUBSCRIPCIÓN</a>
        </div>
        <div className={styles.right}>
          <a className={styles.log} href="">Log In</a>
          <a href=""><img className={styles.lupa} src="lupa.png"/></a>
        </div>

      </div>
      

      <div className={styles.datos}>
        {
          data.map(dat => (
            <div key = {dat.id}>
              <h2 className={styles.resu}> Resultados de trazabilidad</h2>

              <div>
                <h4> Numero de registro = {dat.id}</h4>
                <h4> Posición en x = {dat['x-pos']} </h4>
                <h4>{dat.tag}</h4>
              </div>

              <div>
                <h4> Temperatura = {dat.temperatura}</h4>
                <h4> Humedad = {dat.humedad}</h4>   
              </div>
              
                                     
            </div>
          ))
        }
     </div>

    </div>
  )
}

export const getServerSideProps = async (context)=>{
  const options = {method: 'GET'};
  const res = await fetch("https://bat-simple-api.vercel.app/data", options)
  const datos = await res.json() 
  
    return {
     props: {
       data : datos
     }
   }
}
