import Head from 'next/head'
import Image from 'next/image'       
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png"/> 
      </Head>     

      <div>
        {
          data.map(dat => (
            <div key = {dat.id}>
              <h4>humedad = {dat.humedad}</h4>
              <h4>temperatura = {dat.temperatura}</h4>
              <h4>posición en x = {dat['x-pos']}</h4>
              <h4>posición en y = {dat['y-pos']}</h4>
              <h4>{dat.tag}</h4>
            </div>
          ))
        }
     </div>

    </div>
  )
}

export const getServerSideProps = async (context)=>{
  const options = {method: 'GET'};
  const res = await fetch("https://bat-simple-api.vercel.app/data", options)
  const datos = await res.json() 
  
    return {
     props: {
       data : datos
     }
   }
}
